'use strict';

import React from 'react';

class Page extends React.Component {
  constructor () {
    super();
  }

  render () {
    return (
      <div>
        <header id="header">
          <div className="row">
            <div className="logo-icon"></div>
            <div className="page-header">{this.props.header}</div>
          </div>
        </header>
        <main id="body">
          <div id="container" className="page-container">
            {this.props.children}
          </div>
        </main>
        <footer>
          <div className="footer">
            Generated by <a href="https://github.com/jefreesujit/react-generator-node">react-generator-node</a>.
          </div>
        </footer>
      </div>
    );
  }
}

Page.displayName = 'Page';

export default Page;
