'use strict';

import React from 'react';

class Page extends React.Component {
  constructor () {
    super();

    this.state = {
      error: false
    };
  }

  componentDidCatch (error) {
    console.log(error);
    this.setState({
      error: true
    });
  }

  getErrorContent () {
    return (
      <div className="page-error-content">
        Some Error occured. We regret for inconvinience.
      </div>
    );
  }

  render () {
    return (
      <div className={this.props.className}>
        <header id="header">
          <div className="row">
            <div className="logo-icon"></div>
            <div className="page-header">{this.props.header}</div>
          </div>
        </header>
        <main id="body">
          <div id="container" className="page-container">
            {this.state.error
              ?  this.getErrorContent()
              : this.props.children}
          </div>
        </main>
        <footer>
          <div className="footer">
            Generated by <a href="https://github.com/jefreesujit/generator-react-node">generator-react-node</a>.
          </div>
        </footer>
      </div>
    );
  }
}

Page.displayName = 'Page';

export default Page;
